# These are supported funding model platforms

github: sc2ad
patreon: sc2ad
custom: ['https://www.paypal.me/sc2ad', 'https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=XQP4GZDKK69DQ&currency_code=USD&source=url']
