// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/Models/beatmap.proto

#include "protobuf/Models/beatmap.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_protobuf_2fModels_2fcharacteristic_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_Characteristic_protobuf_2fModels_2fcharacteristic_2eproto;
namespace TournamentAssistantShared {
namespace Models {
class BeatmapDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<Beatmap> _instance;
} _Beatmap_default_instance_;
}  // namespace Models
}  // namespace TournamentAssistantShared
static void InitDefaultsscc_info_Beatmap_protobuf_2fModels_2fbeatmap_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::TournamentAssistantShared::Models::_Beatmap_default_instance_;
    new (ptr) ::TournamentAssistantShared::Models::Beatmap();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Beatmap_protobuf_2fModels_2fbeatmap_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_Beatmap_protobuf_2fModels_2fbeatmap_2eproto}, {
      &scc_info_Characteristic_protobuf_2fModels_2fcharacteristic_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_protobuf_2fModels_2fbeatmap_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_protobuf_2fModels_2fbeatmap_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_protobuf_2fModels_2fbeatmap_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_protobuf_2fModels_2fbeatmap_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::TournamentAssistantShared::Models::Beatmap, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::TournamentAssistantShared::Models::Beatmap, name_),
  PROTOBUF_FIELD_OFFSET(::TournamentAssistantShared::Models::Beatmap, level_id_),
  PROTOBUF_FIELD_OFFSET(::TournamentAssistantShared::Models::Beatmap, characteristic_),
  PROTOBUF_FIELD_OFFSET(::TournamentAssistantShared::Models::Beatmap, difficulty_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::TournamentAssistantShared::Models::Beatmap)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::TournamentAssistantShared::Models::_Beatmap_default_instance_),
};

const char descriptor_table_protodef_protobuf_2fModels_2fbeatmap_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\035protobuf/Models/beatmap.proto\022 Tournam"
  "entAssistantShared.Models\032$protobuf/Mode"
  "ls/characteristic.proto\032(protobuf/Models"
  "/beatmap_difficulty.proto\"\274\001\n\007Beatmap\022\014\n"
  "\004name\030\001 \001(\t\022\020\n\010level_id\030\002 \001(\t\022H\n\016charact"
  "eristic\030\003 \001(\01320.TournamentAssistantShare"
  "d.Models.Characteristic\022G\n\ndifficulty\030\004 "
  "\001(\01623.TournamentAssistantShared.Models.B"
  "eatmapDifficultyB#\252\002 TournamentAssistant"
  "Shared.Modelsb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_protobuf_2fModels_2fbeatmap_2eproto_deps[2] = {
  &::descriptor_table_protobuf_2fModels_2fbeatmap_5fdifficulty_2eproto,
  &::descriptor_table_protobuf_2fModels_2fcharacteristic_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_protobuf_2fModels_2fbeatmap_2eproto_sccs[1] = {
  &scc_info_Beatmap_protobuf_2fModels_2fbeatmap_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_protobuf_2fModels_2fbeatmap_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protobuf_2fModels_2fbeatmap_2eproto = {
  false, false, descriptor_table_protodef_protobuf_2fModels_2fbeatmap_2eproto, "protobuf/Models/beatmap.proto", 381,
  &descriptor_table_protobuf_2fModels_2fbeatmap_2eproto_once, descriptor_table_protobuf_2fModels_2fbeatmap_2eproto_sccs, descriptor_table_protobuf_2fModels_2fbeatmap_2eproto_deps, 1, 2,
  schemas, file_default_instances, TableStruct_protobuf_2fModels_2fbeatmap_2eproto::offsets,
  file_level_metadata_protobuf_2fModels_2fbeatmap_2eproto, 1, file_level_enum_descriptors_protobuf_2fModels_2fbeatmap_2eproto, file_level_service_descriptors_protobuf_2fModels_2fbeatmap_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_protobuf_2fModels_2fbeatmap_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_protobuf_2fModels_2fbeatmap_2eproto)), true);
namespace TournamentAssistantShared {
namespace Models {

// ===================================================================

class Beatmap::_Internal {
 public:
  static const ::TournamentAssistantShared::Models::Characteristic& characteristic(const Beatmap* msg);
};

const ::TournamentAssistantShared::Models::Characteristic&
Beatmap::_Internal::characteristic(const Beatmap* msg) {
  return *msg->characteristic_;
}
void Beatmap::clear_characteristic() {
  if (GetArena() == nullptr && characteristic_ != nullptr) {
    delete characteristic_;
  }
  characteristic_ = nullptr;
}
Beatmap::Beatmap(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:TournamentAssistantShared.Models.Beatmap)
}
Beatmap::Beatmap(const Beatmap& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_name().empty()) {
    name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_name(), 
      GetArena());
  }
  level_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_level_id().empty()) {
    level_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_level_id(), 
      GetArena());
  }
  if (from._internal_has_characteristic()) {
    characteristic_ = new ::TournamentAssistantShared::Models::Characteristic(*from.characteristic_);
  } else {
    characteristic_ = nullptr;
  }
  difficulty_ = from.difficulty_;
  // @@protoc_insertion_point(copy_constructor:TournamentAssistantShared.Models.Beatmap)
}

void Beatmap::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_Beatmap_protobuf_2fModels_2fbeatmap_2eproto.base);
  name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  level_id_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&characteristic_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&difficulty_) -
      reinterpret_cast<char*>(&characteristic_)) + sizeof(difficulty_));
}

Beatmap::~Beatmap() {
  // @@protoc_insertion_point(destructor:TournamentAssistantShared.Models.Beatmap)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void Beatmap::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  level_id_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete characteristic_;
}

void Beatmap::ArenaDtor(void* object) {
  Beatmap* _this = reinterpret_cast< Beatmap* >(object);
  (void)_this;
}
void Beatmap::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Beatmap::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Beatmap& Beatmap::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_Beatmap_protobuf_2fModels_2fbeatmap_2eproto.base);
  return *internal_default_instance();
}


void Beatmap::Clear() {
// @@protoc_insertion_point(message_clear_start:TournamentAssistantShared.Models.Beatmap)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmpty();
  level_id_.ClearToEmpty();
  if (GetArena() == nullptr && characteristic_ != nullptr) {
    delete characteristic_;
  }
  characteristic_ = nullptr;
  difficulty_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Beatmap::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "TournamentAssistantShared.Models.Beatmap.name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string level_id = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_level_id();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "TournamentAssistantShared.Models.Beatmap.level_id"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .TournamentAssistantShared.Models.Characteristic characteristic = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ctx->ParseMessage(_internal_mutable_characteristic(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .TournamentAssistantShared.Models.BeatmapDifficulty difficulty = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          ::PROTOBUF_NAMESPACE_ID::uint64 val = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
          _internal_set_difficulty(static_cast<::TournamentAssistantShared::Models::BeatmapDifficulty>(val));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* Beatmap::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TournamentAssistantShared.Models.Beatmap)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TournamentAssistantShared.Models.Beatmap.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // string level_id = 2;
  if (this->level_id().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_level_id().data(), static_cast<int>(this->_internal_level_id().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "TournamentAssistantShared.Models.Beatmap.level_id");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_level_id(), target);
  }

  // .TournamentAssistantShared.Models.Characteristic characteristic = 3;
  if (this->has_characteristic()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        3, _Internal::characteristic(this), target, stream);
  }

  // .TournamentAssistantShared.Models.BeatmapDifficulty difficulty = 4;
  if (this->difficulty() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteEnumToArray(
      4, this->_internal_difficulty(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TournamentAssistantShared.Models.Beatmap)
  return target;
}

size_t Beatmap::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TournamentAssistantShared.Models.Beatmap)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string level_id = 2;
  if (this->level_id().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_level_id());
  }

  // .TournamentAssistantShared.Models.Characteristic characteristic = 3;
  if (this->has_characteristic()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *characteristic_);
  }

  // .TournamentAssistantShared.Models.BeatmapDifficulty difficulty = 4;
  if (this->difficulty() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::EnumSize(this->_internal_difficulty());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Beatmap::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:TournamentAssistantShared.Models.Beatmap)
  GOOGLE_DCHECK_NE(&from, this);
  const Beatmap* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<Beatmap>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:TournamentAssistantShared.Models.Beatmap)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:TournamentAssistantShared.Models.Beatmap)
    MergeFrom(*source);
  }
}

void Beatmap::MergeFrom(const Beatmap& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:TournamentAssistantShared.Models.Beatmap)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {
    _internal_set_name(from._internal_name());
  }
  if (from.level_id().size() > 0) {
    _internal_set_level_id(from._internal_level_id());
  }
  if (from.has_characteristic()) {
    _internal_mutable_characteristic()->::TournamentAssistantShared::Models::Characteristic::MergeFrom(from._internal_characteristic());
  }
  if (from.difficulty() != 0) {
    _internal_set_difficulty(from._internal_difficulty());
  }
}

void Beatmap::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:TournamentAssistantShared.Models.Beatmap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Beatmap::CopyFrom(const Beatmap& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TournamentAssistantShared.Models.Beatmap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Beatmap::IsInitialized() const {
  return true;
}

void Beatmap::InternalSwap(Beatmap* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  level_id_.Swap(&other->level_id_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Beatmap, difficulty_)
      + sizeof(Beatmap::difficulty_)
      - PROTOBUF_FIELD_OFFSET(Beatmap, characteristic_)>(
          reinterpret_cast<char*>(&characteristic_),
          reinterpret_cast<char*>(&other->characteristic_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Beatmap::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Models
}  // namespace TournamentAssistantShared
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::TournamentAssistantShared::Models::Beatmap* Arena::CreateMaybeMessage< ::TournamentAssistantShared::Models::Beatmap >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TournamentAssistantShared::Models::Beatmap >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
