// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/Models/packet_type.proto

#include "protobuf/Models/packet_type.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace TournamentAssistantShared {
namespace Models {
}  // namespace Models
}  // namespace TournamentAssistantShared
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_protobuf_2fModels_2fpacket_5ftype_2eproto = nullptr;
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_protobuf_2fModels_2fpacket_5ftype_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_protobuf_2fModels_2fpacket_5ftype_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_protobuf_2fModels_2fpacket_5ftype_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_protobuf_2fModels_2fpacket_5ftype_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n!protobuf/Models/packet_type.proto\022 Tou"
  "rnamentAssistantShared.Models*\222\002\n\nPacket"
  "Type\022\023\n\017Acknowledgement\020\000\022\013\n\007Command\020\001\022\013"
  "\n\007Connect\020\002\022\023\n\017ConnectResponse\020\003\022\t\n\005Even"
  "t\020\004\022\010\n\004File\020\005\022\024\n\020ForwardingPacket\020\006\022\016\n\nL"
  "oadedSong\020\007\022\014\n\010LoadSong\020\010\022\014\n\010PlaySong\020\t\022"
  "\014\n\010Response\020\n\022\020\n\014ScoreRequest\020\013\022\030\n\024Score"
  "RequestResponse\020\014\022\020\n\014SongFinished\020\r\022\014\n\010S"
  "ongList\020\016\022\017\n\013SubmitScore\020\017B#\252\002 Tournamen"
  "tAssistantShared.Modelsb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_protobuf_2fModels_2fpacket_5ftype_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_protobuf_2fModels_2fpacket_5ftype_2eproto_sccs[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_protobuf_2fModels_2fpacket_5ftype_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protobuf_2fModels_2fpacket_5ftype_2eproto = {
  false, false, descriptor_table_protodef_protobuf_2fModels_2fpacket_5ftype_2eproto, "protobuf/Models/packet_type.proto", 391,
  &descriptor_table_protobuf_2fModels_2fpacket_5ftype_2eproto_once, descriptor_table_protobuf_2fModels_2fpacket_5ftype_2eproto_sccs, descriptor_table_protobuf_2fModels_2fpacket_5ftype_2eproto_deps, 0, 0,
  schemas, file_default_instances, TableStruct_protobuf_2fModels_2fpacket_5ftype_2eproto::offsets,
  file_level_metadata_protobuf_2fModels_2fpacket_5ftype_2eproto, 0, file_level_enum_descriptors_protobuf_2fModels_2fpacket_5ftype_2eproto, file_level_service_descriptors_protobuf_2fModels_2fpacket_5ftype_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_protobuf_2fModels_2fpacket_5ftype_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_protobuf_2fModels_2fpacket_5ftype_2eproto)), true);
namespace TournamentAssistantShared {
namespace Models {
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PacketType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_protobuf_2fModels_2fpacket_5ftype_2eproto);
  return file_level_enum_descriptors_protobuf_2fModels_2fpacket_5ftype_2eproto[0];
}
bool PacketType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Models
}  // namespace TournamentAssistantShared
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
