// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/Models/Packets/submit_score.proto

#include "protobuf/Models/Packets/submit_score.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_protobuf_2fModels_2fscore_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_Score_protobuf_2fModels_2fscore_2eproto;
namespace TournamentAssistantShared {
namespace Models {
namespace Packets {
class SubmitScoreDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SubmitScore> _instance;
} _SubmitScore_default_instance_;
}  // namespace Packets
}  // namespace Models
}  // namespace TournamentAssistantShared
static void InitDefaultsscc_info_SubmitScore_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::TournamentAssistantShared::Models::Packets::_SubmitScore_default_instance_;
    new (ptr) ::TournamentAssistantShared::Models::Packets::SubmitScore();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_SubmitScore_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_SubmitScore_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto}, {
      &scc_info_Score_protobuf_2fModels_2fscore_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::TournamentAssistantShared::Models::Packets::SubmitScore, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::TournamentAssistantShared::Models::Packets::SubmitScore, score_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::TournamentAssistantShared::Models::Packets::SubmitScore)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::TournamentAssistantShared::Models::Packets::_SubmitScore_default_instance_),
};

const char descriptor_table_protodef_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n*protobuf/Models/Packets/submit_score.p"
  "roto\022(TournamentAssistantShared.Models.P"
  "ackets\032\033protobuf/Models/score.proto\"E\n\013S"
  "ubmitScore\0226\n\005score\030\001 \001(\0132\'.TournamentAs"
  "sistantShared.Models.ScoreB+\252\002(Tournamen"
  "tAssistantShared.Models.Packetsb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto_deps[1] = {
  &::descriptor_table_protobuf_2fModels_2fscore_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto_sccs[1] = {
  &scc_info_SubmitScore_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto = {
  false, false, descriptor_table_protodef_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto, "protobuf/Models/Packets/submit_score.proto", 239,
  &descriptor_table_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto_once, descriptor_table_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto_sccs, descriptor_table_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto_deps, 1, 1,
  schemas, file_default_instances, TableStruct_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto::offsets,
  file_level_metadata_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto, 1, file_level_enum_descriptors_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto, file_level_service_descriptors_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto)), true);
namespace TournamentAssistantShared {
namespace Models {
namespace Packets {

// ===================================================================

class SubmitScore::_Internal {
 public:
  static const ::TournamentAssistantShared::Models::Score& score(const SubmitScore* msg);
};

const ::TournamentAssistantShared::Models::Score&
SubmitScore::_Internal::score(const SubmitScore* msg) {
  return *msg->score_;
}
void SubmitScore::clear_score() {
  if (GetArena() == nullptr && score_ != nullptr) {
    delete score_;
  }
  score_ = nullptr;
}
SubmitScore::SubmitScore(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:TournamentAssistantShared.Models.Packets.SubmitScore)
}
SubmitScore::SubmitScore(const SubmitScore& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_score()) {
    score_ = new ::TournamentAssistantShared::Models::Score(*from.score_);
  } else {
    score_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:TournamentAssistantShared.Models.Packets.SubmitScore)
}

void SubmitScore::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_SubmitScore_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto.base);
  score_ = nullptr;
}

SubmitScore::~SubmitScore() {
  // @@protoc_insertion_point(destructor:TournamentAssistantShared.Models.Packets.SubmitScore)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SubmitScore::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete score_;
}

void SubmitScore::ArenaDtor(void* object) {
  SubmitScore* _this = reinterpret_cast< SubmitScore* >(object);
  (void)_this;
}
void SubmitScore::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SubmitScore::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SubmitScore& SubmitScore::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SubmitScore_protobuf_2fModels_2fPackets_2fsubmit_5fscore_2eproto.base);
  return *internal_default_instance();
}


void SubmitScore::Clear() {
// @@protoc_insertion_point(message_clear_start:TournamentAssistantShared.Models.Packets.SubmitScore)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && score_ != nullptr) {
    delete score_;
  }
  score_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SubmitScore::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .TournamentAssistantShared.Models.Score score = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_score(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SubmitScore::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:TournamentAssistantShared.Models.Packets.SubmitScore)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .TournamentAssistantShared.Models.Score score = 1;
  if (this->has_score()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::score(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:TournamentAssistantShared.Models.Packets.SubmitScore)
  return target;
}

size_t SubmitScore::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:TournamentAssistantShared.Models.Packets.SubmitScore)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .TournamentAssistantShared.Models.Score score = 1;
  if (this->has_score()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *score_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SubmitScore::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:TournamentAssistantShared.Models.Packets.SubmitScore)
  GOOGLE_DCHECK_NE(&from, this);
  const SubmitScore* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SubmitScore>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:TournamentAssistantShared.Models.Packets.SubmitScore)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:TournamentAssistantShared.Models.Packets.SubmitScore)
    MergeFrom(*source);
  }
}

void SubmitScore::MergeFrom(const SubmitScore& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:TournamentAssistantShared.Models.Packets.SubmitScore)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_score()) {
    _internal_mutable_score()->::TournamentAssistantShared::Models::Score::MergeFrom(from._internal_score());
  }
}

void SubmitScore::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:TournamentAssistantShared.Models.Packets.SubmitScore)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SubmitScore::CopyFrom(const SubmitScore& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:TournamentAssistantShared.Models.Packets.SubmitScore)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SubmitScore::IsInitialized() const {
  return true;
}

void SubmitScore::InternalSwap(SubmitScore* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(score_, other->score_);
}

::PROTOBUF_NAMESPACE_ID::Metadata SubmitScore::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace Packets
}  // namespace Models
}  // namespace TournamentAssistantShared
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::TournamentAssistantShared::Models::Packets::SubmitScore* Arena::CreateMaybeMessage< ::TournamentAssistantShared::Models::Packets::SubmitScore >(Arena* arena) {
  return Arena::CreateMessageInternal< ::TournamentAssistantShared::Models::Packets::SubmitScore >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
